//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Houses
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
    }
}
